name("T5").
name("T7").
name("Urquhart-s3-b1.shuffled").
name("Urquhart-s3-b10.shuffled").
name("Urquhart-s3-b2.shuffled").
name("Urquhart-s3-b3.shuffled").
name("Urquhart-s3-b4.shuffled").
name("Urquhart-s3-b5.shuffled").
name("Urquhart-s3-b6.shuffled").
name("Urquhart-s3-b7.shuffled").
name("Urquhart-s3-b8.shuffled").
name("Urquhart-s3-b9.shuffled").
name("Urquhart-s4-b1.shuffled").
name("Urquhart-s4-b10.shuffled").
name("Urquhart-s4-b2.shuffled").
name("Urquhart-s4-b3.shuffled").
name("Urquhart-s4-b4.shuffled").
name("Urquhart-s4-b5.shuffled").
name("Urquhart-s4-b6.shuffled").
name("Urquhart-s4-b7.shuffled").
name("Urquhart-s4-b8.shuffled").
name("Urquhart-s4-b9.shuffled").
name("Urquhart-s5-b1.shuffled").
name("Urquhart-s5-b10.shuffled").
name("Urquhart-s5-b2.shuffled").
name("Urquhart-s5-b3.shuffled").
name("Urquhart-s5-b4.shuffled").
name("Urquhart-s5-b5.shuffled").
name("Urquhart-s5-b6.shuffled").
name("Urquhart-s5-b7.shuffled").
name("Urquhart-s5-b8.shuffled").
name("Urquhart-s5-b9.shuffled").
name("hole20").
name("hole30").
name("hole40").
name("hole50").
name("mchess-10").
name("mchess-20").
name("mchess-30").
name("mchess-40").
name("mchess-50").
name("tph12").
name("tph16").
name("tph20").
name("tph8").
name("M3").
name("M4").
name("M5").
name("M6").
name("M7").
name("M8").
name("M9").
name("M10").