
conv_time("T5",0).
conv_time("T7",0).
conv_time("Urquhart-s3-b1.shuffled",0).
conv_time("Urquhart-s3-b10.shuffled",0).
conv_time("Urquhart-s3-b2.shuffled",0).
conv_time("Urquhart-s3-b3.shuffled",0).
conv_time("Urquhart-s3-b4.shuffled",0).
conv_time("Urquhart-s3-b5.shuffled",0).
conv_time("Urquhart-s3-b6.shuffled",0).
conv_time("Urquhart-s3-b7.shuffled",0).
conv_time("Urquhart-s3-b8.shuffled",0).
conv_time("Urquhart-s3-b9.shuffled",0).
conv_time("Urquhart-s4-b1.shuffled",0).
conv_time("Urquhart-s4-b10.shuffled",0).
conv_time("Urquhart-s4-b2.shuffled",0).
conv_time("Urquhart-s4-b3.shuffled",0).
conv_time("Urquhart-s4-b4.shuffled",0).
conv_time("Urquhart-s4-b5.shuffled",0).
conv_time("Urquhart-s4-b6.shuffled",0).
conv_time("Urquhart-s4-b7.shuffled",0).
conv_time("Urquhart-s4-b8.shuffled",0).
conv_time("Urquhart-s4-b9.shuffled",0).
conv_time("Urquhart-s5-b1.shuffled",0).
conv_time("Urquhart-s5-b10.shuffled",0).
conv_time("Urquhart-s5-b2.shuffled",0).
conv_time("Urquhart-s5-b3.shuffled",0).
conv_time("Urquhart-s5-b4.shuffled",0).
conv_time("Urquhart-s5-b5.shuffled",0).
conv_time("Urquhart-s5-b6.shuffled",0).
conv_time("Urquhart-s5-b7.shuffled",0).
conv_time("Urquhart-s5-b8.shuffled",0).
conv_time("Urquhart-s5-b9.shuffled",0).
conv_time("hole20",0).
conv_time("hole30",0).
conv_time("hole40",20).
conv_time("hole50",60).
conv_time("mchess-10",0).
conv_time("mchess-20",10).
conv_time("mchess-30",40).
conv_time("mchess-40",120).
conv_time("mchess-50",290).
conv_time("tph12",10).
conv_time("tph16",30).
conv_time("tph20",160).
conv_time("tph8",0).
conv_time("M3",0).
conv_time("M4",0).
conv_time("M5",0).
conv_time("M6",0).
conv_time("M7",0).
conv_time("M8",20).
conv_time("M9",70).
conv_time("M10",280).
