name("T5").
name("T7").
name("Urquhart-s5-b1.shuffled").
name("Urquhart-s5-b2.shuffled").
name("Urquhart-s5-b3.shuffled").
name("Urquhart-s5-b4.shuffled").
name("hole20").
name("hole30").
name("hole40").
name("hole50").
name("mchess-10").
name("mchess-20").
name("mchess-30").
name("mchess-40").
name("mchess-50").
name("tph8").
name("tph12").
name("tph16").
name("tph20").